name: MTL Maritime Services
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3875909149646759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#ededed'
    - '#b2b2b2'
    - '#7deff1'
    - '#eb7624'
  brandStrength: 0.3433201243169606
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.6501605720259249
purpose: []
